pipeline {
    agent any
    tools {
        jdk 'Java 21' // Nom exact du JDK que tu as configuré dans Jenkins
    }

    environment {
        IMAGE_NAME = 'Blockchain_Layer'
        TAG = "${env.BUILD_NUMBER ?: 'local'}"
        DOCKER_REGISTRY = 'docker.io/khazrisalah2004'
        DOCKER_CREDENTIALS_ID = 'dockerhub-credentials'
    }

    stages {
        stage('Checkout') {
            steps { checkout scm }
        }
        stage('Build Maven') {
            steps {
                dir('Backend/Blockchain_Layer') {
                    bat '.\\mvnw.cmd -B -DskipTests clean package'
                }
            }
        }
        stage('Build Docker image') {
            steps {
                dir('Backend/Blockchain_Layer') {
                    script {
                        def imageFull = "${env.DOCKER_REGISTRY}/${env.IMAGE_NAME}:${env.TAG}"
                        bat "docker build -t ${imageFull} ."
                        env.IMAGE_FULL = imageFull
                    }
                }
            }
        }
        
        stage('Push Docker image') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: env.DOCKER_CREDENTIALS_ID, usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        bat 'echo %DOCKER_PASS% | docker login docker.io --username %DOCKER_USER% --password-stdin'
                        bat "docker push ${env.IMAGE_FULL}"
                    }
                }
            }
        }
    }
}
